from app.routers.auth import router as auth_router
from app.routers.categories import router as categories_router
from app.routers.services import router as services_router
from app.routers.users import router as users_router
from app.routers.orders import router as orders_router
from app.routers.saved import router as saved_router
from app.routers.messages import router as messages_router
from app.routers.profile import router as profile_router
from app.routers.payments import router as payments_router
from app.routers.admin import router as admin_router
from app.routers.customer_service import router as customer_service_router
from app.routers.admin_cs import router as admin_cs_router
